id=oauth2
name=OAuth2 / OpenID Connect Provider
version=${project.version}
description=Connects to an OAuth2 / OpenID Connect authorization server, to introspect access tokens or to retrieve user info.
class=io.gravitee.resource.oauth2.generic.OAuth2GenericResource
type=resource
icon=oauth2.svg
category=OAuth2
